process.on('uncaughtException', (err) => {
    console.log(err);
});
